### PR TITLE
Add pnpm support

### PR DESCRIPTION
**Pull request by ConstasJ**

### CODE REVIEW

**Comment by shigma** [comment]
This PR does not really add pnpm support.

**Comment by ConstasJ** [comment]
What I do is adding pnpm-workspace.yml to enable pnpm workspaces in this monorepo repository.I think after that this repo can use pnpm.  
So why do you think that this PR do not really add pnpm support?

**Comment by shigma** [comment]
> I think after that this repo can use pnpm.

It actually can not.

1. Koishi does not and will not support ths *isolated linker* so you need to configurate your `.npmrc` file.
2. This PR does not help users of Koishi, only to provide incomplete support for official repository developers. However developers in the official repository should follow the prerequisites which includes using our recommended package managers. Introduction of pnpm means that more edge cases may continue to be introduced in the future, which the development team did not need and should not consider.

**Comment by ConstasJ** [comment]
しかし、僕はまだpnpmを使用する方がyarnを使用するよりもはるかに良い選択だと思います。

**Comment by ilharp** [comment]
1. According to corepack practice one project can only choose one single PM to use.

2. There have been many reports that **Koishi cannot start using pnpm**. See [document](https://koishi.js.org/manual/starter/boilerplate.html).

**Comment by ilharp** [comment]
I recommend locking PM for Koishi to avoid possible future problems:

```diff
  {
    "name": "@root/koishi",
    "private": true,
+   "packageManager": "yarn@1.22.19",
    "workspaces": [
```

**Comment by ConstasJ** [comment]
Please review this Pull Request.
### **Please!!!**

**Review by shigma — APPROVED** [review]

**Pull request merged**
