### PR TITLE
fix(database-mongo): Windows does not listen to localhost by default

### PR DESCRIPTION
**Pull request by idanran**

### CODE REVIEW

**Comment by idanran** [comment]
> what is the problem would be solved in this PR? Theoretically the localhost and the 127.0.0.1 is equivalent, And you should not set the default port in this case because MongoDB requires no port in a SRV protocol. see: #629

Then remove the port

**Comment by idanran** [comment]
> what is the problem would be solved in this PR? Theoretically the localhost and the 127.0.0.1 is equivalent, And you should not set the default port in this case because MongoDB requires no port in a SRV protocol. see: #629

This PR solves the `MongoServerSelectionError: connect ECONNREFUSED ::1:27017`

**Comment by MaikoTan** [comment]
> This PR solves the `MongoServerSelectionError: connect ECONNREFUSED ::1:27017`

obviously The localhost settings in your PC is set to the IPV6 protocol￼￼￼ that caused the problem?￼

**Comment by idanran** [comment]
> > This PR solves the `MongoServerSelectionError: connect ECONNREFUSED ::1:27017`
> 
> obviously The localhost settings in your PC is set to the IPV6 protocol￼￼￼ that caused the problem?￼

I can not confirm

**Comment by Anillc** [comment]
> > > This PR solves the `MongoServerSelectionError: connect ECONNREFUSED ::1:27017`
> > 
> > 
> > obviously The localhost settings in your PC is set to the IPV6 protocol￼￼￼ that caused the problem?￼
> 
> I can not confirm

check your hosts file

**Comment by MaikoTan** [comment]
> > > > This PR solves the `MongoServerSelectionError: connect ECONNREFUSED ::1:27017`
> > > 
> > > 
> > > obviously The localhost settings in your PC is set to the IPV6 protocol￼￼￼ that caused the problem?￼
> > 
> > I can not confirm
> 
> check your hosts file

Yup, that's the problem. But I'm skeptical that mongodb didn't support ipv6 address.

**Pull request closed without merging**
