### PR TITLE
Use MariaDB for example docker-compose database

### PR DESCRIPTION
**Pull request by purerosefallen**
I think MariaDB is always better than MySQL, especially when it comes to MySQL 5.7.

### CODE REVIEW

**Comment by Shigma** [comment]
Koishi use MySQL 5.7 features such as `JSON` type, which I'm not sure whether is supported by MariaDB. I am not very familiar with the use of MariaDB. Can you confirm it?

**Comment by purerosefallen** [comment]
> Koishi use MySQL 5.7 features such as `JSON` type, which I'm not sure whether is supported by MariaDB. I am not very familiar with the use of MariaDB. Can you confirm it?

MariaDB 10 is 100% compatitable with MySQL 5.7...

**Comment by Shigma** [comment]
Sounds fine. I'll investigate mariadb for koishi by myself later.

**Comment by Shigma** [comment]
Provided by anillc:

image

**Pull request merged**
