### PR TITLE
fix(telegram): Use URL to parse file uri, fix #743

### LINKED ISSUE #743: Bug: telegram adapter不能正确处理本地文件的file uri
### Describe the bug

使用telegram adapter发送本地文件，目前只能支持`file://path`形式的uri，根据file uri的格式，正确的形式应该是 `file:/path` 和 `file:///path`，但这两种形式都会导致发送错误。

https://en.wikipedia.org/wiki/File_URI_scheme

目前gocqhttp支持单三斜杠，不支持双斜杠，导致不管用哪种写法都会冲突。

### Steps to reproduce

```
argv.session.send(segment('image', {
        url: 'file:///' + fullPath
      }))
```
以三个斜杠的file uri写法发送图片

### Expected behavior

图片正常发送

### Screenshots

_No response_

### Versions

- OS: Windows 11
- Platform: telegram
- Node version: 16.15.0
- Koishi version: 4.7.6

### Additional context

https://github.com/koishijs/koishi/blob/bc3b50479e95951e2295664752293e218ef53971/plugins/adapter/telegram/src/sender.ts#L24-L27

目前schema和path的解析是靠://字符串拆分，使用 [URL](https://nodejs.org/api/url.html#urlprotocol) 进行解析可能会更加安全，
[fileURLToPath](https://nodejs.org/api/url.html#urlfileurltopathurl) 可以进行路径的转换。

### PR DESCRIPTION
**Pull request by samnyan**
See koishijs/issues#7

### CODE REVIEW

**Review by shigma — COMMENTED** [review]
Actually this part of the code will be moved to a new repository (https://github.com/satorijs/node-sdk). I surely can merge this PR now, but you can also choose to submit a PR directly to the new repository after the next release, depending on which repository you want to contribute to.

**Comment by shigma** [comment]
@samnyan Are you willing to open a pull request at satorijs/satori?

**Comment by samnyan** [comment]
Yes I will open a pr there.

**Comment by shigma** [comment]
Closed in favor of satorijs/satori@f65094763f6e02e4c002b2e3e060d2595abe6f16.

**Pull request closed without merging**
